#[macro_use]
extern crate text_io;

fn converter(){
    println!("Enter Number:  ");
    let inpt_number: i32 = read!();

    match inpt_number {
        1 => println!("I"),
        2 => println!("II"),
        3 => println!("III"),
        4 => println!("IV"),
        5 => println!("V"),
        6 => println!("VI"),
        7 => println!("VII"),
        8 => println!("VIII"),
        9 => println!("IX"),
        10 => println!("X"),
        11 => println!("XI"),
        12 => println!("XII"),
        13 => println!("XIII"),
        14 => println!("XIV"),
        15 => println!("XV"),
        16 => println!("XVI"),
        17 => println!("XVII"),
        18 => println!("XVIII"),
        19 => println!("XIX"),
        20 => println!("XX"),
        21 => println!("XXI"),
        22 => println!("XXII"),
        23 => println!("XXIII"),
        24 => println!("XXIV"),
        25 => println!("XXV"),
        26 => println!("XXVI"),
        27 => println!("XXVII"),
        28 => println!("XXVIII"),
        29 => println!("XXIX"),
        30 => println!("XXX"),
        31 => println!("XXXI"),
        32 => println!("XXXII"),
        33 => println!("XXXIII"),
        34 => println!("XXXIV"),
        35 => println!("XXXV"),
        36 => println!("XXXVI"),
        37 => println!("XXXVII"),
        38 => println!("XXXVIII"),
        39 => println!("XXXIX"),
        40 => println!("XL"),
        41 => println!("XLI"),
        42 => println!("XLII"),
        43 => println!("XLIII"),
        44 => println!("XLIV"),
        45 => println!("XLV"),
        46 => println!("XLVI"),
        47 => println!("XLVII"),
        48 => println!("XLVIII"),
        49 => println!("XLIX"),
        50 => println!("L"),
        51 => println!("LI"),
        52 => println!("LII"),
        53 => println!("LIII"),
        54 => println!("LIV"),
        55 => println!("LV"),
        56 => println!("LVI"),
        57 => println!("LVII"),
        58 => println!("LVIII"),
        59 => println!("LIX"),
        60 => println!("LX"),
        61 => println!("LXI"),
        62 => println!("LXII"),
        63 => println!("LXIII"),
        64 => println!("LXIV"),
        65 => println!("LXV"),
        66 => println!("LXVI"),
        67 => println!("LXVII"),
        68 => println!("LXVIII"),
        69 => println!("LXIX"),
        70 => println!("LXX"),
        71 => println!("LXXI"),
        72 => println!("LXXII"),
        73 => println!("LXXIII"),
        74 => println!("LXXIV"),
        75 => println!("LXXV"),
        76 => println!("LXXVI"),
        77 => println!("LXXVII"),
        78 => println!("LXXVIII"),
        79 => println!("LXXIX"),
        80 => println!("LXXX"),
        81 => println!("LXXXI"),
        82 => println!("LXXXII"),
        83 => println!("LXXXIII"),
        84 => println!("LXXXIV"),
        85 => println!("LXXXV"),
        86 => println!("LXXXVI"),
        87 => println!("LXXXVII"),
        88 => println!("LXXXVIII"),
        89 => println!("LXXXIX"),
        90 => println!("XC"),
        91 => println!("XCI"),
        92 => println!("XCII"),
        93 => println!("XCIII"),
        94 => println!("XCIV"),
        95 => println!("XCV"),
        96 => println!("XCVI"),
        97 => println!("XCVII"),
        98 => println!("XCVIII"),
        99 => println!("XCIX"),
        100 => println!("C"),
        1000 => println!("M"),
        _ => println!("Failed to recognise input, acceptable numbers: 1-100, 1000"),
    }  
}

fn main(){
    converter();
}